// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALIlRD2hWqS_TJQXJhKAFI70zeCX0OehE',
    appId: '1:176696682958:web:e618efbdb2b7fb40a6e39f',
    messagingSenderId: '176696682958',
    projectId: 'citizen128-f0ad8',
    authDomain: 'citizen128-f0ad8.firebaseapp.com',
    storageBucket: 'citizen128-f0ad8.firebasestorage.app',
    measurementId: 'G-V3ZJ1BJS5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Hu09iCDkkqjhzI5Tv9BM_BWBKDrg17E',
    appId: '1:176696682958:android:72508aabcc0e0656a6e39f',
    messagingSenderId: '176696682958',
    projectId: 'citizen128-f0ad8',
    storageBucket: 'citizen128-f0ad8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUrVhyuJpV7205LQGrzDD17fNqB-xIpVw',
    appId: '1:176696682958:ios:8f48edde2b9cc00aa6e39f',
    messagingSenderId: '176696682958',
    projectId: 'citizen128-f0ad8',
    storageBucket: 'citizen128-f0ad8.firebasestorage.app',
    iosBundleId: 'com.citizen128.citizen128',
  );
}
